### PR TITLE
Timeshift improvements & build fixes

### PR DESCRIPTION
**Pull request by manuelm**
* Make sure bufferpath exists
* Truncate buffer file on stop

### CODE REVIEW

**Comment by manuelm** [comment]
@CiNcH83 This should fix your remaining problems. Not tested yet.

**Comment by CiNcH83** [comment]
Can you pull it into the master?

**Comment by manuelm** [comment]
On December 26, 2016 4:46:19 PM GMT+01:00, CiNcH83 <notifications@github.com> wrote:
>Can you pull it into the master?

Next year :-)

**Comment by CiNcH83** [comment]
Buffer path checks seem to work beautifully. When I connect the USB storage, I get the 'Pause' button. When I remove it, the 'Pause' button is not shown anymore. It is not even necessary to restart Kodi. So CanPause is most likely called whenever the player controls are brought up.

Buffer truncation also works.

**Comment by CiNcH83** [comment]
Something I haven't tried... what happens if the storage runs out of space? I hope the buffer file does not get truncated in this case?

**Comment by CiNcH83** [comment]
OK, I tried that now on Windows, where I have a bit more control over everything than on Android. Behaviour is as wanted. It is still possible to play to the buffer end after running out of space which is good. I assume that the behaviour is the same on all supported operating systems.

**Comment by manuelm** [comment]
> So CanPause is most likely called whenever the player controls are brought up.

No, all the time, a few hundred times per minute. So this checks adds a bit of latency due to the underlying stat syscall.

> what happens if the storage runs out of space?

write call fails so all new data is lost.

**Comment by CiNcH83** [comment]
Are you planning to release this stuff with Leia? Or maybe Krypton 17.1?

**Comment by manuelm** [comment]
No idea if a 17.1 is gonna happen. But it will be in L.

**Comment by CiNcH83** [comment]
At least there is a milestone defined for 17.1, see [here](https://github.com/xbmc/xbmc/milestone/99).

**Pull request merged**
