### PR TITLE
Fixes and enhancments for group recordings in Krypton

### PR DESCRIPTION
**Pull request by heikobihr**
Hi,

I did some fixes and enhancments to pvr.dvbviewer in Krypton branch:

1)
I fixed a bug to make group recordings by directory name work properly.

2)
Add option to group by title

3)
Do not create groups with one element, only. These recordings will be shown at top level instead.
Old behavior can be forced by a user setting.

Regards
Heiko

### CODE REVIEW

**Comment by manuelm** [comment]
Thanks for the enhancements. I'll comment on a couple of things but beforehand please only add translations for `en_gb`, all others have to be added through transiflex. So remove those files please.

Also I like the new `groups on demand`-feature but don't want to add new options. They are already too much. So please enable this feature for the your new `by title` only. It don't think this option makes sense for the others.

**Comment by heikobihr** [comment]
OK, I'll remove translations other than `en_gb`.

Having a simple settings dialog is definitely something to aim for :-)

Maybe `groups on demand` makes sense for `by series` or `by recording directory` as well? This will save users a click to access recordings, if these would be the only recording in a group.
However, when grouping `by series` or `by recording directory` users may want to explcitely have groups, even with one recording only.

I'll remove the option as suggested and enable `groups on demand` for group `by title`only.

**Comment by MartijnKaijser** [comment]
remember that this is against Krytpon branch so if you also want them in the future you'll have to do them for master as well.

**Comment by manuelm** [comment]
Thanks Martijn. @heikobihr can you rebase against master please?

**Comment by manuelm** [comment]
> Maybe groups on demand makes sense for by series or by recording directory as well? This will save users a click to access recordings, if these would be the only recording in a group.

Main reason against is: users won't find single recordings in the expected sorting because different recording information get mixed. e.g. for `by series` users will see folders named after the series intermixed with the title of single recordings.

**Comment by heikobihr** [comment]
close due to request to rebase on master (see #65)

**Pull request closed without merging**
