### PR TITLE
Get rid of external kodiplatform dependency

### PR DESCRIPTION
**Pull request by basilgello**
1. Import XMLUtils.h from pvr.vuplus and change
   "namespace enigma2" to "namespace dvbviewer"

2. Open the affected files manually and re-order includes:

   nano $(git grep -l "XMLUtils.h")

   Also add "using namespace dvbviewer::utilities" and replace
   "XMLUtils::" with "xml::"

3. Remove libkodiplatform-dev form debian/control file

4. Remove kodiplatform from CMakeLists.txt and add XMLUtils.h
   to local header list.

Signed-off-by: Vasyl Gello <vasek.gello@gmail.com>

### CODE REVIEW

**Comment by phunkyfish** [comment]
If someone could test this change that would be great.

**Comment by manuelm** [comment]
> replace "XMLUtils::" with "xml::"

Can you revert this part please? I see no benefit in this.

Edit: And ofc rename the namespace in the header

**Comment by basilgello** [comment]
> > replace "XMLUtils::" with "xml::"
> 
> Can you revert this part please? I see no benefit in this.
> 
> Edit: And ofc rename the namespace in the header

Done! Thanks! :)

**Review by phunkyfish — APPROVED** [review]
👍

**Review by manuelm — APPROVED** [review]

**Pull request merged**
