### PR TITLE
adapt to PVR API 5.2.0

### PR DESCRIPTION
**Pull request by janbar**

### CODE REVIEW

**Comment by manuelm** [comment]
You know that your changes aren't the same and in fact it breaks the playback of ongoing recordings, right? Just calling `OnPlay` in `OpenRecordedStream` isn't a sufficient replacement. Otherwise I would have done this in the first place.

**Comment by janbar** [comment]
What is this strange thing ?

**Comment by janbar** [comment]
Annoucement interface is definitely dropped.

**Comment by janbar** [comment]
Have you a other way to manage this instead waiting for an announcement ?

**Comment by manuelm** [comment]
Well, playback of ongoing recordings doesn't need much explaining. The code in fact does.
Kodis file/url wrappers don't recognize filesize changes. So I need to close+reopen the file stream every x seconds. Otherwise the size will be read on startup and the playback will stop after the initial size is reached.

The OnPlay-announcement is a hack to workaround a bug(?) in ffmpeg/the player/somewhere. If the filesize changes during the initial buffering phase, the playback will stop immediately.

Actually this is all kind of a hack. Best solution would be to integrate curl or some other http library so I can fetch the stream and check the new filesize on my own. But I'm lacking time.

What's the current timeframe for Kodi.next?

**Comment by janbar** [comment]
The other way could be to set playback on the first call of ReadRecordedStream(). It will have same behavior.

**Comment by manuelm** [comment]
No. As I said I need a way to determine if the ffmpeg buffering is finished. `ReadRecordedStream` can't do that.

**Comment by janbar** [comment]
Can we count readen bytes and then set the flag after 1MB ? Or you required to set the flag exactly when buffering is completed ?

**Comment by manuelm** [comment]
Afair I tried something like that. Will take a look in May.
Can you remove the call to `OnPlay` please? That way the playback will stop after the initial file size is reached but playback should at least work.

**Comment by janbar** [comment]
Yes sure as you need.

**Comment by janbar** [comment]
related to xbmc/xbmc#9662

**Comment by manuelm** [comment]
Thanks @janbar

**Pull request merged**
