### PR TITLE
Backports for Krypton

### PR DESCRIPTION
**Pull request by manuelm**
...in case someone wants to test features/fixes on Krypton

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
@manuelm 
how about we just make repo the main upstream (since you maintain it) and deprecate this one?
Only thing you have to do is create github release tags including addon version bumps and send a bump request to here
https://github.com/xbmc/repo-binary-addons (master and Krypton branch).

For transifex language updates you will have to give @txtranslation push access to your repo and we get @alanwww1 to change the base location to where it pushes update.

That saves you all this work of backporting these changes.

**Comment by manuelm** [comment]
@MartijnKaijser 
Thanks for the offer but after thinking about the implication I'd rather prefer to keep the repos as is. Main reason is my build machines are pulling from my repo and if a build issue comes up (usually on windows) I prefer to quickly do commit+build until it's fixed and squash them later. Also I can't force push anymore :smile_cat:

**Comment by MartijnKaijser** [comment]
to remedy that you could also create some dev branches next to the "release" branches :)
Once you're sure you could push the commit from dev branch to "release" branch. Just a thought.

**Comment by manuelm** [comment]
Yeah, I know, but right now my build environment requires the pvr with the kodi/xbmc branch to match. Otherwise it might compile against the wrong headers. Any good idea how to solve that other than hardcoding (like I did in the `appveyor.yml`)?

**Comment by CiNcH83** [comment]
Buffer path checks seem to work beautifully. When I connect the USB storage, I get the 'Pause' button. When I remove it, the 'Pause' button is not shown anymore. It is not even necessary to restart Kodi. So CanPause is most likely called whenever the player controls are brought up.

Buffer truncation also works.

**Pull request merged**
